--CONSULTAS DE COMBINACION
--ESTE TIPO DE CONSULTA NOS PERMITE OBTENER DATOS DE 2 O MÁS TABLAS QUE ESTEN RELACIONADOS ENTRE SÍ

--CON UNA CONSULTA OBTENEMOS VARIOS DATOS

-- LAS TABLAS DEBEN TENER UN CAMPO DE RELACION ENTRE SI PARA FUNCIONAR

-- TENEMOS LA TABLA DE EMPLEADOS
SELECT * FROM EMP;

--Ahora mismo con esto no podemos saber DONDE TRABAJA JIMENEZ PORQUE LAS TABLAS DE EMPLEADOS Y DEPARTAMENTOS ESTÁN SEPARADOS

SELECT * FROM DEPT;

--SINTAXIS:
/*
SELECT TABLA1.CAMPO, TABLA1.CAMPO2,
TABLA2.CAMPO, TABLA2.CAMPO2
FROM TABLA1
INNER JOIN TABLA2
ON TABLA1.CAMPODERELACION = TABLA2.CAMPODERELACION;
*/
-- NOTA: NO IMPORTA EL ORDEN DEL 'INNER JOIN' Y NO IMPORTA EL ORDEN EN EL 'ON'

--AHORA MOSTRAMOS EL APELLIDO, OFICIO, NOMBRE DE DEPARTAMENTO Y LOCALIDAD DE LOS EMPLEADOS
SELECT EMP.APELLIDO, EMP.OFICIO,
DEPT.DNOMBRE, DEPT.LOC
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO;

-- POR SUPUESTO, PODEMOS ESCRIBIR UN WHERE SIN PROBLEMAS.
--DEBEMOS PENSAR QUE FROM ES COMPUESTO

--MOSTRAMOS APELLIDO, OFICIO, NOMBRE DEPARTAMENTO Y LOCALIZACION DE LOS EMPLEADOS DE SEVILLA
SELECT EMP.APELLIDO, EMP.OFICIO,
DEPT.DNOMBRE, DEPT.LOC
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
WHERE DEPT.LOC = 'SEVILLA';

--PODMEOS TOMARNOS CIERTAS LICENCIAS AL ESCRIBIR ESTAS CONSULTAS. 
--ELEMENTOS QUE PODEMOS HACER SIN CUMPLIR LAS REGLAS. MALA PRAXIS
    --NO ES OBLIGATORIO PONER EL NOMBRE DE LA TABLA DE DONDE RECUPERAMOS DATOS NI EN SELECT NI EN WHERE
    --LA RAZÓN DE PONER LA TABLA A LA QUE PERTENECE ES PARA FACILITAR LAS COSAS Y MOSTRAR DE DONDE SALEN LLOS DATOS

-- SI EL DATO QUE VAMOS A MOSTRAR ES EL QUE SE RELACIONA ENTRE AMBAS SI QUE HAY QUE ESPECIFICAR DE QUE TABLA ES

--EN CONSULTAS DE ESTE TIPO PODEMOS PONER ALIAS A LOS NOMBRES DE LAS TABLAS
--EN CASO DE PONER ALIAS DEBEMOS USARLO DURANTE TODA LA CONSULTA
--ALIAS EN NOMBRE DE TABLA
SELECT E.APELLIDO, E.OFICIO,
D.DNOMBRE, D.LOC
FROM EMP E
INNER JOIN DEPT D
ON E.DEPT_NO = D.DEPT_NO
WHERE D.LOC = 'SEVILLA';

--Visualizamos el apellido, especialidad, nombre de hospital, direccion de hospital de los doctores

SELECT DOCTOR.APELLIDO, DOCTOR.ESPECIALIDAD,
HOSPITAL.NOMBRE, HOSPITAL.DIRECCION
FROM DOCTOR
INNER JOIN HOSPITAL
ON DOCTOR.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD
ORDER BY HOSPITAL.NOMBRE;

--OBVIAMENTE ESTO SE PUEDE COMBINAR CON CONSULTAS D EAGRUPACION
--MOSTRAMOS EL NUMERO DE PERSONAS POR CADA DEPARTAMENTOS DE LOS EMPLEADOS

SELECT COUNT(*) AS EMPLEADOS, DEPT_NO
FROM EMP
GROUP BY DEPT_NO;
--MOSTRAMOS EL NUMERO DE PERSONAS POR CADA NOMBRE DE DEPARTAMENTO DE LOS EMPLEADOS
SELECT COUNT(*) AS EMPLEADOS, DEPT.DNOMBRE, DEPT.DEPT_NO
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
GROUP BY DEPT.DNOMBRE,DEPT.DEPT_NO;

--DENTRO DEL JOIN TENEMOS DIFERENTES OPCIONES DEPENDIENDO DE LOS RESULTADOS QUE DESEAMOS MOSTRAR EN LA COMBINACION
/*
    INNER JOIN: MUESTRA LOS TRESULTADOS QUE COMBINEN DE LAS 2 TABLAS
    LEFT JOIN: MUES LOS RESULTADOS QUE COMBINEN DE AMBAS Y LOS QUE NO COMBINEN DE LA TABLA IZQUIERDA
    NOTA: ES LA ATABLA ANTES DEL JOIN
    RIGHT JOIN: MUESTRA LOS RESULTADOS QUE COMBINEN DE AMBAS Y LOS QUE NO COMBINEN DE LA TABLA DERECHA
    NOTA2: ES LA TABLA DESPUES DEL JOIN
    FULL JOIN: MUESTRA LOS RESULTADOS DE LAS TABLAS COMBINEN O NO
    CROSS JOIN: MUESTRA EL PRODUCTO CARTESIANO
*/

SELECT DISTINCT DEPT_NO FROM EMP;
SELECT * FROM DEPT;

--PARA ESTE EJEMPLO VAMOS A CREAR UN EMPLEADO SIN DEPARTAMENTO, YA QUE HAY UN DEPARTAMNTO SIN EMPLEADOS
--USANDO INNER JOIN EL EMPLEADO SIN DEPT Y EL DEPT SIN EMPLEADOS NO SALEN
SELECT EMP.APELLIDO, EMP.OFICIO,
DEPT.DNOMBRE, DEPT.LOC
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO;
--USANDO LEFT JOIN muestra aquellos que no combinen de los campos mostrados DE LA TABLA IZQUIERDA SOLO
SELECT EMP.APELLIDO, EMP.OFICIO,
DEPT.DNOMBRE, DEPT.LOC
FROM EMP
LEFT JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO;
--USANDO RIGHT JOIN MUESTRA LOS RESULTADOS QUE NO COMBINEN DE LOS CAMPOS MOSTRADOS D ELA TABLA DERECHA
SELECT EMP.APELLIDO, EMP.OFICIO,
DEPT.DNOMBRE, DEPT.LOC
FROM EMP
RIGHT JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO;
--USANDO FULL JOIN MUESTRA TODO PERO EN ESTE CASO NO SERÍA UTIL EN CASO DE SER RELACION N <=> N
SELECT EMP.APELLIDO, EMP.OFICIO,
DEPT.DNOMBRE, DEPT.LOC
FROM EMP
FULL JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO;
--CROSS JOIN: PRODUCTO CARTESIANO saca todas las posibilidades DE LA TABLA 2 SOBRE LA 1
SELECT EMP.APELLIDO, EMP.OFICIO,
DEPT.DNOMBRE, DEPT.LOC
FROM EMP
CROSS JOIN DEPT;

--POR ÚLTIMO PODEMOS REALIZAR JOIN ENTRE MAS DE OS TABLAS
--PARA HACERLO IREMOS INCLUYENDO INNER JOIN Y ON POR TABLA
/* 
SINTAXIS:
    SELECT TABLA1.CAMPO., TABLA1.CAMPO2,
    TABLA2.CAMPO1, TABLA3.CAMPO1
    FROM TABLA1
    INNER JOIN TABLA2
    ON TABLA1.CAMPORELACION = TABLA2.CAMPORELACION
    INNER JOIN TABLA3
    ON TABLA1.CAMPORELACION = TABLA3.CAMPORELACION

*NOTA: LA RELACION DA IGUAL CON CUAL SEA MIENTRA SE RELACIONE CON ALGUNA DE LAS TABLAS
*/

--MOSTRAMOS EL APELLIDO, FUNCION, NOMBRE D EHOSPITAL, DIRECCION Y NOMBRE DE SALA DE LOS EMPLEADOS
--DE LA PLANTILLA
SELECT * FROM HOSPITAL;
SELECT * FROM SALA ORDER BY SALA_COD;
SELECT * FROM PLANTILLA ORDER BY SALA_COD;
SELECT PLANTILLA.APELLIDO, PLANTILLA.FUNCION, HOSPITAL.NOMBRE, HOSPITAL.DIRECCION, SALA.NOMBRE
FROM PLANTILLA
INNER JOIN HOSPITAL
ON PLANTILLA.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD
INNER JOIN SALA
ON HOSPITAL.HOSPITAL_COD = SALA.HOSPITAL_COD
AND PLANTILLA.SALA_COD = SALA.SALA_COD;

--PRACTICAS DE CONSULTAS DE COMBINACIÓN--
--LAS SACO AQUI LAS TALAS--
SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM PLANTILLA;
SELECT * FROM HOSPITAL;

--VISUALIZAMOS LA SUMASALARIAL DE CADA PERSONA DE LA PLANTILLA POR CADA NOMBRE DE HOSPITAL
SELECT COUNT(*) AS NUM_EMPLEADOS, SUM(PLANTILLA.SALARIO) AS SUMA_SALARIAL, HOSPITAL.NOMBRE
FROM PLANTILLA
INNER JOIN HOSPITAL
ON PLANTILLA.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD
GROUP BY HOSPITAL.NOMBRE
ORDER BY SUM(SALARIO) DESC;
--HE AÑADIDO EL EXTRA DE CUANTOS EMPLEADOS HAY POR HOSPITAL

--QUIERO EL NUMERO DE EMPLEADOS QUE TRABAJAN EN CADA LOCALIDAD
SELECT COUNT(EMP.EMP_NO) AS NUM_EMPLEADOS,  DEPT.LOC
FROM EMP
RIGHT JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
GROUP BY DEPT.LOC;
--AQUÍ ME SALE 1 EN GRANADA PORQUE CUENTA EL NULO POR ESO DEBEMOS PONER COUNT(EMP.APELLIDO)
-- CON COUNT(*) ME CUENTA LOS NULOS Y EN ESTE CASO NO VALDRÍA

--Seleccionar el apellido, oficio, salario, numero de departamento y su nombre de todos los empleados cuyo salario sea mayor de 300000
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT EMP.APELLIDO, EMP.OFICIO, EMP.SALARIO,
DEPT.DEPT_NO, DEPT.DNOMBRE
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
WHERE SALARIO > 300000;

--Mostrar todos los nombres de Hospital con sus nombres de salas correspondientes.
SELECT * FROM SALA;
SELECT * FROM HOSPITAL;

SELECT SALA.NOMBRE, HOSPITAL.NOMBRE
FROM SALA
INNER JOIN HOSPITAL
ON SALA.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD;

--Calcular cuántos trabajadores de la empresa hay en cada ciudad.
SELECT COUNT(EMP.EMP_NO) AS NUM_EMPLEADOS,  DEPT.LOC
FROM EMP
RIGHT JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
GROUP BY DEPT.LOC;

--Visualizar cuantas personas realizan cada oficio en cada departamento mostrando el nombre del departamento.

SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT COUNT(EMP.OFICIO) AS TRABAJADORES, EMP.OFICIO, DEPT.DNOMBRE
FROM EMP
RIGHT JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
GROUP BY EMP.OFICIO, DEPT.DNOMBRE;

--Contar cuantas salas hay en cada hospital, mostrando el nombre de las salas y el nombre del hospital.
SELECT COUNT(SALA.SALA_COD) AS NUM_SALAS, SALA.NOMBRE, HOSPITAL.NOMBRE
FROM SALA
INNER JOIN HOSPITAL
ON SALA.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD
GROUP BY SALA.NOMBRE, HOSPITAL.NOMBRE;

--Queremos saber cuántos trabajadores se dieron de alta entre el año 1997 y 1998 y en qué departamento.
SELECT * FROM EMP;

SELECT COUNT(EMP.APELLIDO) AS ALTAS, DEPT.DNOMBRE
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
WHERE EMP.FECHA_ALT BETWEEN '01-01-1997' AND '31-12-1998'
GROUP BY DEPT.DNOMBRE;

--Buscar aquellas ciudades con cuatro o más personas trabajando.

SELECT COUNT(EMP.APELLIDO) AS EMPLEADOS, DEPT.LOC
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
GROUP BY DEPT.LOC
HAVING COUNT(EMP.APELLIDO) >= 4;

--Calcular la media salarial por ciudad.  Mostrar solamente la media para Madrid y Elche.

SELECT AVG(EMP.SALARIO) AS MEDIA_SALARIAL, DEPT.LOC
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
WHERE DEPT.LOC IN ('MADRID', 'SEVILLA')
GROUP BY DEPT.LOC;

--Mostrar los doctores junto con el nombre de hospital en el que ejercen, la dirección y el teléfono del mismo.

SELECT * FROM DOCTOR;
SELECT * FROM HOSPITAL;

SELECT DOCTOR.APELLIDO, HOSPITAL.NOMBRE, HOSPITAL.DIRECCION, HOSPITAL.TELEFONO
FROM DOCTOR
INNER JOIN HOSPITAL
ON DOCTOR.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD;

--Mostrar los nombres de los hospitales junto con el mejor salario de los empleados de la plantilla de cada hospital.
SELECT * FROM HOSPITAL;
SELECT * FROM PLANTILLA;

SELECT HOSPITAL.NOMBRE, MAX(PLANTILLA.SALARIO) AS SALARIO_MAXIMO
FROM HOSPITAL
INNER JOIN PLANTILLA
ON HOSPITAL.HOSPITAL_COD = PLANTILLA.HOSPITAL_COD
GROUP BY HOSPITAL.NOMBRE;

--Visualizar el Apellido, función y turno de los empleados de la plantilla junto con el nombre de la sala y el nombre del hospital con el teléfono.
SELECT * FROM SALA;

SELECT PLANTILLA.APELLIDO, PLANTILLA.FUNCION, PLANTILLA.TURNO, SALA.NOMBRE, HOSPITAL.NOMBRE, HOSPITAL.TELEFONO
FROM PLANTILLA
INNER JOIN SALA
ON PLANTILLA.HOSPITAL_COD = SALA.HOSPITAL_COD
AND PLANTILLA.SALA_COD = SALA.SALA_COD
INNER JOIN HOSPITAL
ON PLANTILLA.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD;

--Visualizar el máximo salario, mínimo salario de los Directores dependiendo de la ciudad en la que trabajen. Indicar el número total de directores por ciudad.
SELECT * FROM EMP
WHERE OFICIO = 'DIRECTOR';

SELECT DEPT.LOC, COUNT(EMP.OFICIO) AS DIRECTORES, MAX(EMP.SALARIO) AS MAXIMO_SALARIO, MIN(EMP.SALARIO) AS MINIMO_SALARIO
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
WHERE EMP.OFICIO = 'DIRECTOR'
GROUP BY DEPT.LOC;

--Averiguar la combinación de que salas podría haber por cada uno de los hospitales.
SELECT * FROM SALA;
SELECT DISTINCT SALA.NOMBRE, COUNT(SALA.NOMBRE) AS NUM_SALAS, HOSPITAL.NOMBRE
FROM SALA
CROSS JOIN HOSPITAL
GROUP BY SALA.NOMBRE, HOSPITAL.NOMBRE;