-- SUBCONSULTAS

--SON MUY UTILES--
/*
    SON CONSULTAS QUE SIN OTRA CONSULTA NO PUEDEN SER EJECUTADAS,
    ES DECIR, NECESITAMOS LOS DATOS D EUNA CONSULTA PARA REALIZARLA.

    EN CONSULTAS D ESELECCION, DEBERIAMOS EVITARLAS YA QUE SUELEN CREAR BLOQUEOS, RALENTIZAN
    LOS REASULTADOS.

    PODEMOS REALIZAR TODA SLAS CONSULTAS QUE DESEEMOS SIN IMPORTAR EL NIVEL DE ANIDAMIENTO

    ANIDAMIENTO:
*/

--EJ: NECESITO LOS DATOS DEL EMPLEADO QUE MAS COBRA EN LA EMPRESA.
--1) NECESITAMOS PRIMERO EL MÁXIMO SALARIO DE LA TABLA EMPLEADOS
SELECT MAX(SALARIO) FROM EMP;
--ME DEVUELVE 650000 Y ESE ES EL SALARIO MAXIMO
--2) UNA VEZ OBTENIDO REALIZAMOS LA CONSULTA PARA MOSTRAR LOS DATOS DEL EMPLEADO
SELECT * FROM EMP WHERE SALARIO = 650000;
--ASÍ SE AÑADEN
-- SE ANIDAN ENTRE PARÉNTESIS Y SE IGUALAN A LOS RESULTADOS D ELA OTRA CONSULTA
SELECT * FROM EMP WHERE SALARIO = (SELECT MAX(SALARIO) FROM EMP);

--ALONSO Y SALA
--MOSTRAR TODOS LOS EMPLEADOS CON EL MISMO OFICIO QUE ALONSO
SELECT OFICIO FROM EMP WHERE APELLIDO = 'alonso';
--HACEMOS LA SUBCONSULTA
SELECT * FROM EMP
WHERE OFICIO = (SELECT OFICIO FROM EMP WHERE APELLIDO = 'alonso');
--AHORA TODOS LOS EMPLEADOS QUE TENGAN EL OFICIO DE ALONSO Y COBREN MAS QUE SALA
SELECT SALARIO FROM EMP WHERE APELLIDO = 'sala';
SELECT * FROM EMP
WHERE OFICIO = (SELECT OFICIO FROM EMP WHERE APELLIDO = 'alonso')
AND SALARIO > (SELECT SALARIO FROM EMP WHERE APELLIDO = 'sala');

--CUANDO LA SUBCONSULTA DEVUELVE MAS DE UN VALOR DEBEMOS USAR EL OPERADOR OR
--MOSTRA RLOS EMPLEADOS QUE TENGAN EL MISMO OFICIO QUE jimenez. Y alonso
SELECT OFICIO FROM EMP WHERE APELLIDO = 'alonso'
OR APELLIDO = 'jimenez';

SELECT * FROM EMP
WHERE OFICIO IN (SELECT OFICIO FROM EMP WHERE APELLIDO = 'alonso'
OR APELLIDO = 'jimenez');

--MEDIA SALARIAL DE LOS EMPLEADOS SIN EL PRESIDENTE
SELECT * FROM EMP WHERE OFICIO <> 'PRESIDENTE' ORDER BY SALARIO DESC;
SELECT * FROM EMP WHERE OFICIO <> 'PRESIDENTE' ORDER BY SALARIO;
SELECT * FROM EMP ORDER BY FECHA_ALT;
SELECT * FROM EMP WHERE ROWNUM <= 4 AND OFICIO <> 'PRESIDENTE' ORDER BY SALARIO;

--EL ROWNUM SIRVE PARA CAPAR LAS FILAS QUE VAMOS A MOSTRAR

--PRACTICA--
--Mostrar el número de empleado, el apellido y la fecha de alta del empleado más antiguo de la empresa.
SELECT MIN(FECHA_ALT) FROM EMP;

SELECT EMP_NO, APELLIDO, FECHA_ALT
FROM EMP
WHERE FECHA_ALT = (SELECT MIN(FECHA_ALT) FROM EMP);

--Mostrar el número de empleado, el apellido y la fecha de alta del empleado más moderno de la empresa.
SELECT MAX(FECHA_ALT) FROM EMP;

SELECT EMP_NO, APELLIDO, FECHA_ALT
FROM EMP
WHERE FECHA_ALT = (SELECT MAX(FECHA_ALT) FROM EMP);

--Visualizar el apellido y el salario de los empleados con el mismo oficio que Jiménez.
SELECT OFICIO FROM EMP WHERE APELLIDO = 'jimenez';

SELECT APELLIDO, SALARIO
FROM EMP
WHERE OFICIO = (SELECT OFICIO FROM EMP WHERE APELLIDO = 'jimenez');

--Queremos saber el apellido, oficio, salario y número de departamento de los empleados con salario mayor que el mejor salario del departamento 30.
SELECT MAX(SALARIO) FROM EMP WHERE DEPT_NO = 30;
SELECT * FROM EMP WHERE DEPT_NO <> 30 ORDER BY SALARIO DESC;

SELECT APELLIDO, OFICIO, SALARIO, DEPT_NO
FROM EMP
WHERE SALARIO > (SELECT MAX(SALARIO) FROM EMP WHERE DEPT_NO = 30);

--Mostrar el apellido, la función u oficio, sala o departamento de todos los empleados que trabajen en Empresa o Plantilla.
SELECT EMP.APELLIDO, (EMP.OFICIO) AS FUNCION, (DEPT.DNOMBRE) AS OFICINA 
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
UNION
SELECT PLANTILLA.APELLIDO, PLANTILLA.FUNCION, SALA.NOMBRE FROM PLANTILLA
INNER JOIN SALA
ON PLANTILLA.HOSPITAL_COD = SALA.HOSPITAL_COD
AND PLANTILLA.SALA_COD = SALA.SALA_COD
ORDER BY APELLIDO;

SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM PLANTILLA;
SELECT * FROM SALA;

--Mostrar apellidos y oficio de los empleados del departamento 20 cuyo trabajo sea el mismo que el de cualquier empleado de ventas.
SELECT * FROM EMP WHERE DEPT_NO = 20;
SELECT EMP.OFICIO FROM EMP 
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
WHERE DEPT.DNOMBRE = 'VENTAS';
SELECT OFICIO FROM EMP WHERE DEPT_NO = 20;

SELECT APELLIDO, OFICIO FROM EMP
WHERE OFICIO IN (SELECT EMP.OFICIO FROM EMP 
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
WHERE DEPT.DNOMBRE = 'VENTAS')
AND DEPT_NO = 20;

--Mostrar los empleados que tienen mejor salario que la media de los directores, no incluyendo al presidente.
SELECT AVG(SALARIO) FROM EMP WHERE OFICIO = 'DIRECTOR';
SELECT OFICIO FROM EMP WHERE OFICIO <> 'PRESIDENTE';

SELECT * FROM EMP
WHERE SALARIO > (SELECT AVG(SALARIO) FROM EMP WHERE OFICIO = 'DIRECTOR')
AND OFICIO <> 'PRESIDENTE';

--Mostrar el apellido, función, salario y código de hospital de los empleados de la plantilla que siendo enfermeros o enfermeras pertenecen al hospital SAN CARLOS.
SELECT PLANTILLA.FUNCION
FROM PLANTILLA
INNER JOIN HOSPITAL
ON PLANTILLA.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD
WHERE HOSPITAL.NOMBRE = 'san carlos';
SELECT * FROM HOSPITAL WHERE HOSPITAL.NOMBRE = 'san carlos';

SELECT PLANTILLA.APELLIDO, PLANTILLA.FUNCION, PLANTILLA.SALARIO, PLANTILLA.HOSPITAL_COD, HOSPITAL.NOMBRE
FROM PLANTILLA
INNER JOIN HOSPITAL
ON PLANTILLA.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD
WHERE HOSPITAL.NOMBRE = 'san carlos'
AND PLANTILLA.FUNCION = 'ENFERMERO';

--Averiguar el salario de TODAS las personas de la bbdd, de forma que se aprecien las diferencias salariales entre ellos.
SELECT APELLIDO, OFICIO, SALARIO FROM EMP
UNION 
SELECT APELLIDO, ESPECIALIDAD, SALARIO FROM DOCTOR
UNION
SELECT APELLIDO, FUNCION, SALARIO FROM PLANTILLA
ORDER BY SALARIO DESC;

--Realizar la misma consulta anterior, pero solamente mostraremos las personas que cuyo oficio termine en O.
SELECT * FROM
(SELECT APELLIDO, OFICIO AS FUNCION, SALARIO FROM EMP
UNION 
SELECT APELLIDO, ESPECIALIDAD, SALARIO FROM DOCTOR
UNION
SELECT APELLIDO, FUNCION, SALARIO FROM PLANTILLA) CONSULTA
WHERE CONSULTA.FUNCION LIKE '%O'
ORDER BY CONSULTA.SALARIO DESC;

--Visualizar los datos de los hospitales que tienen personal (Doctores) de cardiología.
SELECT HOSPITAL_COD FROM DOCTOR WHERE ESPECIALIDAD = 'Cardiologia';
SELECT * FROM HOSPITAL;

SELECT * 
FROM HOSPITAL
WHERE HOSPITAL_COD IN (SELECT HOSPITAL_COD FROM DOCTOR WHERE ESPECIALIDAD = 'Cardiologia');

--Visualizar el apellido y el salario anual de los empleados de la plantilla del Hospital Provincial y General.
SELECT (SALARIO * 14), APELLIDO AS SALARIO_ANUAL FROM PLANTILLA WHERE HOSPITAL_COD BETWEEN 18 AND 19;
SELECT * FROM HOSPITAL;

SELECT (SALARIO * 14), APELLIDO AS SALARIO_ANUAL 
FROM PLANTILLA 
WHERE HOSPITAL_COD IN (SELECT HOSPITAL_COD FROM HOSPITAL WHERE HOSPITAL_COD = 18 OR HOSPITAL_COD = 19);

SELECT (PLANTILLA.SALARIO * 14) SALARIO_ANUAL , PLANTILLA.APELLIDO
FROM PLANTILLA
INNER JOIN HOSPITAL
ON PLANTILLA.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD
WHERE HOSPITAL.NOMBRE IN ('provincial', 'general');

--Mostrar el apellido de los enfermos que nacieron antes que el Señor Miller.
SELECT * FROM ENFERMO order by FECHA_NAC desc;

SELECT APELLIDO 
FROM ENFERMO 
WHERE FECHA_NAC > (SELECT FECHA_NAC FROM ENFERMO WHERE APELLIDO like 'Miller%');

--Necesitamos un informe para evaluar cómo van las cuentas generales de la empresa.  
--Para ello, necesitamos saber lo que cobra cada persona por cada oficio de manera detallada.  
--Necesitamos el máximo salario y el mínimo más la media salarial, el total de sueldos y el número de trabajadores que hay en cada puesto de toda la base de datos.
SELECT OFICIO, MAX(SALARIO) AS MAXIMO, AVG(SALARIO) AS MEDIA, MIN(SALARIO) AS MINIMO, SUM(SALARIO) AS SUMA, COUNT(*) AS TRABAJADORES FROM EMP GROUP BY OFICIO;
SELECT * FROM DOCTOR;
SELECT * FROM PLANTILLA;

SELECT OFICIO, MAX(SALARIO) AS MAXIMO, AVG(SALARIO) AS MEDIA, MIN(SALARIO) AS MINIMO, SUM(SALARIO) AS SUMA, COUNT(*) AS TRABAJADORES
FROM (
SELECT APELLIDO, OFICIO, SALARIO FROM EMP
UNION 
SELECT APELLIDO, ESPECIALIDAD, SALARIO FROM DOCTOR
UNION
SELECT APELLIDO, FUNCION, SALARIO FROM PLANTILLA) INFORME
GROUP BY OFICIO
ORDER BY MAX(SALARIO) DESC, OFICIO;