--CONSULTAS DE UNION--
/* TEORIA
    ESTE TIPO DE CONSULTAS SIRVE PARA RECUPERAR DATOS DE VARIAS TABLAS QUE NO TIENEN
    NINGUN TIPO DE RELACION ENTRE SI, PERO QUE SI TIENEN RELACION CONCEPTUAL

    PARA ESTE TIPO D EOCNSULTAS SOLAMENTE TENEMOS QUE SEGUIR 3 NORMAS:

        1) LA PRIMERA CONSULTA ES LA JEFA
        2) TODAS LAS CONSULTAS DEBEN TENER EL MISMO NÚMERO DE COLUMNAS
        3) TODAS LAS COLUMNAS DEBEN TENER EL MISMO TIPO DE DATO ENTRE SI

    ES UNIR CONSULTAS QUE NO TIENEN NADA QUE VER EN UN MISMO CURSOR, ES DECIR, LO QUE SE MUESTRA AL HACER LA REQUEST

    EN NUESTRA BASE DE DATOS, TENEMOS REGISTROS QUE REPRESENTAN PERSONAS, NO TIENE NADA QUE VER ENTRE SÍ, PERO SON PERSONAS.

    ¿QUE SUCEDE SI QUIERO MOSTRAR TODAS LAS PERSONAS EN MI BBDD?

    UNION SUPRIME DUPLICADOS DE FILAS COMPLETAS PERO SI HAY VARIANTES SI LAS MUESTRA
    EN CASO DE QUERER MOSTRAR TODOS PUES USAMOS UNION ALL

    LOS ORDER BY SI QUE AFECTAN A TODAS LAS CONSULTAS
*/

--CONSULTA UNION: EMP, DOCTOR, PLANTILLA
SELECT APELLIDO, OFICIO, SALARIO FROM EMP
UNION 
SELECT APELLIDO, ESPECIALIDAD, SALARIO FROM DOCTOR
UNION
SELECT APELLIDO, FUNCION, SALARIO FROM PLANTILLA
ORDER BY SALARIO;

-- SI YO PONGO ALIAS, SE PONDRÁ EN DE LA PRIMERA CONSULTA PUES ES LA JEFA
-- EN CASO DE QUE QUIERA HACER UN WHERE, SON INDIVIDUALES A CADA CONSULTA EN ESTE CASO SOLO AFECTA A PLANTILLA

SELECT APELLIDO, OFICIO, SALARIO FROM EMP
UNION 
SELECT APELLIDO, OFICIO, SALARIO FROM EMP
UNION 
SELECT APELLIDO, OFICIO, SALARIO FROM EMP;
