--SELECT TO SELECT
/* TEORIA
    PERMITE REALIZAR UN SELECT SOBRE UNA CONSULTA YA REALIZADA. ES HACER UN SELECT SOBRE UN CURSOR

    ES UTIL CUANDO NECESITAMOS REALIZAR UN FILTRO GLOBAL SOBRE UNA CONSULTA UNION O PARA 
    HACER CONSULTAS SIMPLES SOBRE CONSULTAS COMPLEJAS

    NOS PODRÍA PERMITIR FILTRAR POR EL SALARIO O APELLIDO

    TAMBIEN PODRIAMOS FILTRAR POR EL ALIAS DE LAS COLUMNAS CUANDO EXISTEN CAMPOS CALCULADOS 

    PARA REALIZAR ESTA CONSULTA DENCESITAMOS HACER 2 COSAS:

        1) ENVOLVER LA CONSULTA SOBRE LA QUE DESEEMOS REALIZAR EL SELECT ENTRE PARÉNTESIS
        2) QUE LA CONSULTA ENVUELTA TENGA UN ALIAS
    EL ALIAS SE ESTABLE COMO EN LOS JOIN DESPUES DEL PARENTESIS DE LA CONSULTA.
*/
-- QUEREMOS FILTRAR SOBRE EL SUELDO DE TODA LA CONSULTA
SELECT * FROM
(SELECT APELLIDO, OFICIO, SALARIO FROM EMP
UNION 
SELECT APELLIDO, ESPECIALIDAD, SALARIO FROM DOCTOR
UNION
SELECT APELLIDO, FUNCION, SALARIO FROM PLANTILLA) CONSULTA
WHERE CONSULTA.SALARIO > 250000;

--CAMPOS CALCULADOS--
--MOSTRAR EL APELLIDO, OFICIO, SALARIO ANUAL DE LOS EMPLEADOS CUYO SALARIO ANUAL SEA MAYOR A 1500000
SELECT * FROM
(SELECT APELLIDO, OFICIO, (SALARIO * 12) AS SALARIO_ANUAL
FROM EMP) CONSULTA1
WHERE CONSULTA1.SALARIO_ANUAL > 1500000;