--SELECT TO ROW
/* TEORIA
    PERIMITE EVALUAR VALORES DENTRO DE CADA FILA Y CAMBIAR EL RESULTADO A MOSTRAR

    PODRIAMOS DAR FORMATO A LOS DATOS QUE EXISTEN EN LA TABLA Y MOSTRAR OTROS DATOS DISTINTOS.
    EL UN IF EN EL SELECT. LA COLUMNA QUE RESULTA ES UN CAMPO CALCULADO

    SE PUEDE HACER CON LO QUE SEA Y PUEDE CAMBIAR EL TIPO DE DATO

    ESTO NO SOBREESCRIBE AL CAMPO DE LA TABLA REAL, PORQUE DEVUELVE UN CAMPO CALCULADO CON LO UE HAS ESCRITO
*/

/* SINTAXIS
SELECT CAMPO1, CAMPO2,
CASE CAMPO3
    WHEN VALOR1 THEN OTROVALOR1
    WHEN VALOR2 THEN OTROVALOR2
    ELSE OTROVALOR3
END AS NOMBRECAMPOCALCULADO, OTROS CAMPOS QUE QUIERAS
FROM TABLA;

*/
--TENEMOS EL TURNO EN PLANTILLA
SELECT APELLIDO, FUNCION,
CASE TURNO
    WHEN 'T' THEN 'TARDE'
    WHEN 'M' THEN 'MAÑANA'
    ELSE 'NOCHE' 
END AS TURNOBONITO, TURNO
FROM PLANTILLA;