--CONSULTAS DE ACCION--
/*
    ESTE TIPO DE CONSULTAS NOS PERMITEN MODIFICAR LOS REGISTROA QUE TENGAMOS EN UNA TABLA.
    EN TODAS LAS BBDD EXISTEN ESTE TIPO DE CONSULTAS PERO, EN ORACLE, ESTAS CONSULTAS SON TRANSACCIONAL,
    QUIERE DECIR ESO QUE NO SON PERMANENTES A NO SE RQUE LO INDIQUEMOS CON UNA INSTRUCCION.

    SI ELIIMINAMOS UNA FILA, DICHA FILA SE ELIMINA DE FORMA TEMPORAL.

    SOLO EN ORACLE:
        MEDIANTE 2 COMANDOS PODEMOS INDICAR QUE DESEAMOS HACER CON LA CONSULTA DE ACCION

        1. COMMIT: LOS CAMBIOS SON PERMANENTES
        2. ROLLBACK: DESHACE LOS CAMBIOS

    DENTRO DE LAS CONSULTAS DE ACCION TENEMOS 3 INSTRUCCIONES:

        1. INSERT: CREA UN NUEVO REGISTRO (LAS FILAS) EN LA TABLA
        2. DELETE: ELIMITA UNO O MAS REGISTROS DE LA TABLA
        3. UPDATE: MODIFICA UNO O MAS REGISTROS DE LA TABLA

        NOTA: LAS INSTRUCCIONES WHERE FUNCIONAN IGUAL QUE LAS CONSULTAS DE SELECCION, OPERADORES Y TODO
*/

-- INSERT--
--INSERTA UNA NUEVA FILA EN LA TABLA
-- SI QUEREMOS INSERTAR 5 FILAS DEBEMOS USAR 5 INSERTS. VAN DE UNO EN UNO
--HAY 2 TIPOS DE SINTAXIS:
    --1. INSERTAR TODOS LOS VALORES DE LA FILA ( TODOS LOS DATOS D ELA TABLA)
    -- ESTA SINTAXIS UTILIZA LA TABLA COMO BASE PARA LOS VALORES, DEBEMOS ESCRIBIR TODOS LOS VALORES TAL Y COMO ESTÉN EN LA TABLA

--INSERT INTO TALBLA VALUES (VAL1, VAL2, VAL3, ...)

--QUEREMOS INSERTAR UN NUEVO DEPARTAMENTO
SELECT * FROM DEPT;
INSERT INTO DEPT VALUES (50, 'PYTHON', 'ALCOBENDAS');

    --2. INSERTAR SOLAMENTE ALGUNOS VALORES D ELA FILA/TABLA
    --ESTA SINTAXIS PERMITE DEFINIR SOLO ALGUNOS DE LOS VALORES D ELA FILA, NO ES NECESARIO INDICAR TODOS
    -- EL ORDEN DE LOS VALORES DEPENDE DE LAS COLUMNAS QUE YO LE INDIQUE

-- INSERT INTO TABLA (COLUM1, COLUM2) VALUES (VAL1, VAL2);
INSERT INTO DEPT (DEPT_NO , LOC) VALUES ( 51, 'ALICANTE');

--SI QUIERO GUARDAR LOS CAMBIOS
COMMIT;

--DENTRO DE LAS CONSULTAS D EESTE TIPO EXISTE UNA HERRAMIENTA MUY UTIL QUE DEBIAMOS EVITAR, LAS SUBCONSULTAS.
--MNOS PERMITEN RECOPERAR DATOS DINÁMICOS DE LA TABLA/TABLAS PARA USARLO EN LAS ACCIONES

--TENEMOS UNA NUEVA PERSONA EN LA PLANTILLA. SE APELLIDA LOPEZ Y ES ENFERMERA DE TARDE DEL HOSPITAL 22. SALA 6 Y 150000 DE SALARIO
--QUERMEOS INSERTAR ESTE REGISTRO CON EL MAXIMO ID DISPONIBLE PAR ALA TABLA PLANTILLA.ALTER
SELECT * FROM PLANTILLA;
SELECT MAX(EMPLEADO_NO) + 1 FROM PLANTILLA;
--9902
INSERT INTO PLANTILLA
(HOSPITAL_COD, SALA_COD, APELLIDO, FUNCION, TURNO, SALARIO, EMPLEADO_NO)
VALUES (22, 6, 'SUPER LOPEZ', 'ENFERMERA', 'T', 150000, 
(SELECT MAX(EMPLEADO_NO) + 1 FROM PLANTILLA));
ROLLBACK;
--DELETE-- 
--ESTE TIPO DE CONSULTA ELIMINA CERO, UNO O VARIOS REGISTROS A LA VEZ
--CON UN SOL ODELETE PODEMOS ELIMINAR TODA LA TABLA

--SINTAXIS:
    --DELETE FROM TABLA
    --NOTA: SI LA CONSULTA NO TIENE WHERE ELIMINA TODOS LOS REGISTROS DE LA TABLA (CUIDADO)
    --POR SUERTE EN ORACLE PODEMOS HACE ROLLBACK
-- ES MUY CONVENIENTE USAR UN WHERE PARA NO BORRAR LA TABLA

--SINTAXIS:
    --DELETE FROM TABLA WHERE CONDICION;
--BORRAMOS A SUPER LOPEZ
DELETE FROM PLANTILLA WHERE APELLIDO = 'SUPER LOPEZ';

--POR SUPUESTO PODEMOS USAR SUBCONSULTAS PARA NUESTRO WHERE

--ELIMINAR TODA LA PLANTILLA DEL HOSPITAL EL CARMEN
SELECT * FROM PLANTILLA;
SELECT * FROM HOSPITAL;
DELETE FROM PLANTILLA WHERE HOSPITAL_COD = 
(SELECT HOSPITAL_COD FROM HOSPITAL WHERE NOMBRE = 'El Carmen');

--UPDATE--
-- MODIFICA CERO, UNA O VARIAS FILAS DE UNA TABLA
--EN UNA MISMA CONSULTA PODEMOS INDICAR QUE QUERMEOS MODIFICAR MAS DE UNA COLUMNA

--SINTAXIS:
    -- UPDATE TABLA SET CAMPO1 = VALOR1, CAMPO2 = VALOR2......;

    --NOTA: SI NO PONEMOS WHERE MODIFICA TODOS LOS REGISTROS DE LA TABLA

--SUBIR EN 1 TODO EL SALARIO D ELA PLANTILLA
UPDATE PLANTILLA SET SALARIO = SALARIO - 1;

--TODOS LOS ENFERMEROS D ELA PLANTILA SERÁN ENFERMERAS Y SE LES SUBE EL SUELDO EN 1
UPDATE PLANTILLA SET FUNCION = 'ENFERMERA', SALARIO = SALARIO + 1 WHERE FUNCION = 'ENFERMERO';

--POR SUPUESTO EN UPDATE PODEMOS USAR SUBCONSULTAS
--TANTO EN EL SET COMO EN EL WHERE, ESO SI ES EN EL SET SOLO PUEDE DEVOLVERNOS 1 VALOR

--EJEMPLO: LOS EMPLEADOS D ELA SALA 4 SE HAN PUESTO EN HUELGA, DICEN QUE SU COMPI KARPLUS COBRA MAS
--MODIFICAMOS LOS EMPLEADOS DE LA SALA 4 PONIENDO EL MISMO SALARIO QUE KARPLUS
SELECT * FROM PLANTILLA;
UPDATE PLANTILLA SET SALARIO =
(SELECT SALARIO FROM PLANTILLA WHERE APELLIDO = 'karplus w.')
where SALA_COD = 4;

--MODIFICAR EL TURNO A MAÑANA A TODOS LOS D ELA PLANTILLA D ELA SALA DE PSIQUIATRIA
SELECT * FROM PLANTILLA;
SELECT * FROM SALA;
UPDATE PLANTILLA SET TURNO = 'M' WHERE SALA_COD in 
(SELECT SALA_COD FROM SALA WHERE NOMBRE = 'psiquiatria');

--PRACTICAS--
--1- INSERTAR UN NUEVO EMPLEADO EN LA PLANTILLA. APELLIDO CABRALES, SALA 4, TURNO N Y TRABAJARÁ EN EL CARMEN, SU ID DEBE SER EL MÁXIMO

INSERT INTO PLANTILLA (HOSPITAL_COD, SALA_COD, EMPLEADO_NO, APELLIDO, TURNO)VALUES ((SELECT HOSPITAL_COD FROM HOSPITAL WHERE NOMBRE = 'el carmen'), 4, (SELECT MAX(EMPLEADO_NO) + 1 FROM PLANTILLA), 'cabrales p.', 'N');

--2. ELIMINAR D ELA PLANTILLA TODAS LA PERSONAS QUE NO TIENEN HOSPITAL ASIGNADO
SELECT * FROM HOSPITAL;
SELECT * FROM PLANTILLA;

DELETE FROM PLANTILLA WHERE HOSPITAL_COD IS NULL OR HOSPITAL_COD NOT IN (SELECT HOSPITAL_COD FROM HOSPITAL);

--POR ULTIMO LA INSTRUCCION PARA ELIMINAR TODOS LOS REGISTROS DE UNA TABLA DE LA FORMA MAS RAPIDA. PORQUE NO TIENE ROLLBACK
    --TRUNCATE TABLE NOMBRETABLA

--PRACTICAS------------------------------------------------------------------------------------------------------------------

--Dar de alta con fecha actual al empleado José Escriche Barrera como programador perteneciente al departamento de producción.  Tendrá un salario base de 70000 pts/mes y no cobrará comisión. 
INSERT INTO EMP (APELLIDO, OFICIO, SALARIO, COMISION, DEPT_NO, EMP_NO) VALUES ('José Escriche Barrera', 'PROGRAMADOR', 70000, 0, (SELECT DEPT_NO FROM DEPT WHERE DNOMBRE = 'PRODUCCIÓN'), (SELECT MAX(EMP_NO) + 1 FROM EMP));
SELECT * FROM EMP;

--Se quiere dar de alta un departamento de informática situado en Fuenlabrada (Madrid).
SELECT * FROM DEPT;
INSERT INTO DEPT VALUES(52, 'INFORMÁTICA', 'FUENLABRADA');

--El departamento de ventas, por motivos peseteros, se traslada a Teruel, realizar dicha modificación.
SELECT * FROM DEPT;
UPDATE DEPT SET LOC = 'TERUEL' WHERE DNOMBRE = 'VENTAS';

--En el departamento anterior (ventas), se dan de alta dos empleados: Julián Romeral y Luis Alonso.  Su salario base es el menor que cobre un empleado, y cobrarán una comisión del 15% de dicho salario.
INSERT INTO EMP (EMP_NO, APELLIDO, OFICIO, SALARIO, COMISION, DEPT_NO, FECHA_ALT) 
VALUES ((SELECT MAX(EMP_NO) + 1 FROM EMP), 'Julián Romeral', 'EMPLEADO', (SELECT MIN(SALARIO) FROM EMP WHERE OFICIO = 'EMPLEADO'), 
(SELECT MIN(SALARIO) * 0.15 FROM EMP WHERE OFICIO = 'EMPLEADO'), (SELECT DEPT_NO FROM DEPT WHERE DNOMBRE = 'VENTAS'), '09-02-2026');

--Modificar la comisión de los empleados de la empresa, de forma que todos tengan un incremento del 10% del salario.
UPDATE EMP SET COMISION = COMISION + (SALARIO * 0.10);
SELECT * FROM EMP;

--Incrementar un 5% el salario de los interinos de la plantilla que trabajen en el turno de noche.
UPDATE PLANTILLA SET SALARIO = SALARIO + (SALARIO * 0.05) WHERE FUNCION = 'INTERINO' AND TURNO = 'N';

--Incrementar en 5000 Pts. el salario de los empleados del departamento de ventas y del presidente, tomando en cuenta los que se dieron de alta antes que el presidente de la empresa.

UPDATE EMP SET SALARIO = SALARIO + 5000 WHERE OFICIO = 'PRESIDENTE' OR FECHA_ALT < (SELECT FECHA_ALT FROM EMP WHERE OFICIO = 'PRESIDENTE') AND DEPT_NO = (SELECT DEPT_NO FROM DEPT WHERE DNOMBRE = 'VENTAS');

--El empleado Sancha ha pasado por la derecha a un compañero.  Debe cobrar de comisión 12.000 ptas más que el empleado Arroyo y su sueldo se ha incrementado un 10% respecto a su compañero.
UPDATE EMP SET COMISION = (SELECT COMISION FROM EMP WHERE APELLIDO = 'arroyo') + 12000, 
SALARIO = (SELECT SALARIO FROM EMP WHERE APELLIDO = 'arroyo') + (SELECT SALARIO * 0.1 FROM EMP WHERE APELLIDO = 'arroyo') 
WHERE APELLIDO = 'sanchez';

--Se tienen que desplazar cien camas del Hospital SAN CARLOS para un Hospital de Venezuela.  Actualizar el número de camas del Hospital SAN CARLOS.
UPDATE HOSPITAL SET NUM_CAMA = NUM_CAMA - 100 WHERE NOMBRE = 'san carlos';

--Subir el salario y la comisión en 100000 pesetas y veinticinco mil pesetas respectivamente a los empleados que se dieron de alta en este año.
UPDATE EMP SET SALARIO = SALARIO + 100000, COMISION = COMISION + 25000 WHERE FECHA_ALT BETWEEN '01-01-2026' AND '31-12-2026';

--Ha llegado un nuevo doctor a la Paz.  Su apellido es House y su especialidad es Diagnostico.   Introducir el siguiente número de doctor disponible.
SELECT * FROM DOCTOR;
select * from hospital;
INSERT INTO DOCTOR (HOSPITAL_COD, APELLIDO, ESPECIALIDAD, DOCTOR_NO) VALUES ((SELECT HOSPITAL_COD FROM HOSPITAL WHERE NOMBRE = 'la paz'), 'House P.', 'Diagnostico', (SELECT MAX(DOCTOR_NO) + 1 FROM DOCTOR));

--Borrar todos los empleados dados de alta entre las fechas 01/01/80 y 31/12/82.
SELECT * FROM EMP ORDER BY FECHA_ALT; 
DELETE FROM EMP WHERE FECHA_ALT BETWEEN '01-01-1980' AND '31-12-1982';

--Modificar el salario de los empleados trabajen en la paz y estén destinados a Psiquiatría.  Subirles el sueldo 20000 Ptas. más que al señor Amigo R.
SELECT * FROM HOSPITAL;
SELECT * FROM dept;
SELECT * FROM emp;

ROLLBACK;
