--FUNCIONES DE AGRUPACIÓN

--MOSTRAMOS EN NUMERO DE EMPLEADOS
SELECT COUNT(*) AS EMPLEADOS FROM EMP;

--PODEMOS CONBINAR VARIAS FUNCIONES
--MOSTRAMOS EL NUMERO DE EMPLEADOS Y LA SUMA SALARIAL DE TODOS

SELECT COUNT(*) AS EMPLEADOS, 
SUM(SALARIO) AS SUMA_SALARIAL FROM EMP;

--LO QUE NOS INTERESA EN ESTAS CONSULTAS ES AGRUPAR POR OTRO DATO
--POR EJEMPLO CUANTAS PERSONAS HAY POR OFICIO
    -- LA AGRUPACION SE REALIZA EN EL SELECT CON LA COLUMNA QUE DESEES ADEMAS D ELA FUNCIÓN DE AGRUPACIÓN
    -- DESPUES DEL FROM INDICAMOS LOS CAMPOS POR LOS QUE ESTAMOS AGRUPANDO MEDIANTE LA INSTRUCCION GROUP BY

SELECT COUNT(*) AS TRABAJOS, OFICIO FROM EMP GROUP BY OFICIO;

--MOSTRAR EL MAXIMO SALARIO, NUMERO DE PERSONAS POR CADA OFICIO Y POR CADA DEPT

SELECT MAX(SALARIO) AS MAX_SALARIO, COUNT(OFICIO) AS EMPLEADOS, OFICIO, 
DEPT_NO FROM EMP GROUP BY OFICIO, DEPT_NO;

--MOSTRAR NUMERO DE PERSONAS
SELECT COUNT(*) AS PERSONAS, OFICIO FROM EMP
WHERE OFICIO IN ('ANALISTA', 'DIRECTOR')
GROUP BY OFICIO;

--EJEMPLO CON HAVING
--MOSTRAR EL NUMERO DE EMPLEADOS POR CADA OFICIO PERO SOLAMENTE MOSTRANDO LOS OFICIO DONDE HAYA MAS DE 2 PERSONAS TRABAJANDO

SELECT COUNT(OFICIO) AS PERSONAS, OFICIO FROM EMP GROUP BY OFICIO HAVING COUNT(*) > 2;

--MOSTRAR LA SUMA SALARIAS POR CADA OFICIO
--SOLAMENTE LAS PERSONAS CON COMISION MAYOR A 0

SELECT SUM(SALARIO) AS SUMASALARIAL, OFICIO
FROM EMP
WHERE COMISION > 0
GROUP BY OFICIO
HAVING SUM(SALARIO) > 515000;

SELECT * FROM EMP;

SELECT MAX(SALARIO) AS MAXSALARIO, OFICIO FROM EMP GROUP BY OFICIO;

SELECT COUNT(OFICIO) AS EMPLEADOS, OFICIO FROM EMP GROUP BY OFICIO HAVING COUNT(OFICIO) >= 4;

SELECT COUNT(*) AS EMPLEADOS, FUNCION FROM PLANTILLA WHERE FUNCION IN ('INTERINO','ENFERMERO','ENFERMERA') GROUP BY FUNCION ORDER BY FUNCION;

SELECT COUNT(*) AS EMPLEADOS, OFICIO, DEPT_NO FROM EMP GROUP BY OFICIO, DEPT_NO HAVING COUNT(*) >= 2;

SELECT AVG(SALARIO) AS MEDIASALARIO, COUNT(*) AS EMPLEADOS, FUNCION FROM PLANTILLA WHERE SALA_COD = 6 GROUP BY FUNCION;

SELECT * FROM EMP;  

SELECT MAX(FECHA_ALT) AS FECHA, OFICIO FROM EMP GROUP BY OFICIO ORDER BY FECHA DESC;

SELECT COUNT(*) AS EMPLEADAS, SALA_COD FROM PLANTILLA WHERE FUNCION = 'ENFERMERA' GROUP BY SALA_COD;

SELECT * FROM ENFERMO;        

SELECT DISTINCT SEXO FROM ENFERMO;

select * from enfermo WHERE INSCRIPCION;

select * from hospital ORDER BY HOSPITAL_COD;

UPDATE DEPT SET LOC = 'TERUEL' WHERE LOC = 'Teruel';

SELECT PLANTILLA.APELLIDO, PLANTILLA.SALARIO, HOSPITAL.NOMBRE
FROM PLANTILLA
INNER JOIN HOSPITAL
ON PLANTILLA.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD
WHERE HOSPITAL.NOMBRE = 'san carlos';

UPDATE PLANTILLA SET SALARIO = SALARIO + 0 WHERE HOSPITAL_COD = (SELECT HOSPITAL_COD FROM HOSPITAL WHERE NOMBRE = 'san carlos');
ROLLBACK;
SELECT HOSPITAL_COD FROM HOSPITAL WHERE NOMBRE = 'san carlos';